services:
  ecommerce-retail-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-retail-api-container
    ports:
      - "8000:8000"
    environment:
      APP_ENV: local
    volumes:
      - ./retail_intelligence.db:/app/retail_intelligence.db
    restart: unless-stopped